# -*- coding: utf-8 -*-
import re

html_path = './smoke_test_runner.html'
with open(html_path, 'r', encoding='utf-8') as f:
    html = f.read()

# Define complete site-specific scenario dictionary in JS
site_scenarios_js = """
        // Dedicated Scenario Suites per Hospital Site
        const siteScenarioFlows = {
            NUH: [
                { id: "SC-01", flow: "OPD", name: "NUH: ลงทะเบียน คัดกรอง ก่อนเข้าตรวจ OPD", desc: "ผู้ป่วย Walk-in ลงทะเบียนระบบ NUH-HIS แล้วถูกส่งต่อไปแผนกคัดกรอง และ เข้าคิว OPD", role: "เวชระเบียน / พยาบาลคัดกรอง / พยาบาล OPD (NUH)", critical: true, steps: "1. ค้นหา/สร้าง HN ใน NUH-HIS -> ลงทะเบียน Visit -> พิมพ์ใบนำทาง NUH\\n2. พยาบาลคัดกรองดู tab 'คำขอ Walk-in' -> บันทึก Vital Sign -> เลือกแพทย์/นัด -> พิมพ์บัตรคิว\\n3. คิวขึ้น tab 'รอเช็คอิน' -> กด Check-in -> กดเรียกคิว -> กด 'พร้อมตรวจ'", criteria: "สถานะผู้ป่วยเปลี่ยนเป็น 'กำลังดำเนินการ' และคิวแสดงหน้าห้องตรวจ NUH" },
                { id: "SC-02 [A]", flow: "OPD", name: "NUH: แพทย์ตรวจ + วินิจฉัย + สั่ง Order (Lab/X-ray/ยา)", desc: "พยาบาลหน้าห้องตรวจ NUH กดเรียกคิว ตรวจผู้ป่วย OPD พร้อมกัน เพื่อเข้าห้องตรวจ แล้วสั่ง Order", role: "แพทย์ OPD / พยาบาลหน้าห้องตรวจ (NUH)", critical: false, steps: "1. พยาบาลกดเรียกคิวเข้าห้องตรวจ NUH\\n2. แพทย์เปิด NUH-EMR เปลี่ยนสถานะ 'พร้อม' -> บันทึก Diagnosis (ICD-10)\\n3. สั่ง Order ครบ 3 ชนิด (Lab + X-ray + ยา) ลงตะกร้า -> กด 'ส่งคำสั่ง' (Submit Order)", criteria: "ส่ง Order ทั้งหมดสำเร็จในครั้งเดียว และสถานะผู้ป่วยเปลี่ยนเป็น 'พักการตรวจ'" },
                { id: "SC-03", flow: "OPD", name: "NUH: ส่ง Lab/X-ray -> รับผล -> แพทย์อ่านผลต่อ", desc: "ระบบ NUH ส่ง Order ไปห้อง Lab/X-ray และประมวลผล Lab/X-ray พร้อมแพทย์อ่านผลกลับเข้าตรวจต่อ", role: "จนท. Lab / แพทย์ OPD (NUH)", critical: false, steps: "1. จนท. Lab เช็คอินรายการ -> เก็บตัวอย่าง (Container) -> ยืนยัน -> ลงผล Lab -> กด Final Report\\n2. แพทย์เปิด NUH-EMR ดูผล -> เปลี่ยนสถานะ 'พร้อม' -> สั่งยาเพิ่ม/นัดหมาย/ออกใบรับรองแพทย์ -> กด 'ตรวจเสร็จ'", criteria: "ผล Lab ออกสมบูรณ์ และแพทย์เปลี่ยนสถานะผู้ป่วยเป็น 'ตรวจเสร็จ'" },
                { id: "SC-04", flow: "OPD", name: "NUH: เภสัชกรรม (สร้างใบยา) -> ชำระเงิน -> เภสัชกรรม จ่ายยา -> การเงินปิด Visit", desc: "เภสัชกร NUH สร้างใบยาส่งต่อการเงินชำระเงินแล้วเภสัชกรจ่ายยาปิด Visit ให้ผู้ป่วย OPD", role: "เภสัชกร OPD / การเงิน (NUH)", critical: false, steps: "1. เภสัชกรตรวจใบสั่งยา -> กด 'สร้างใบยา' -> กด 'ยืนยันใบยา' (ตัด Stock ยา NUH)\\n2. การเงินออกใบแจ้งหนี้ -> รับชำระเงิน -> พิมพ์ใบเสร็จ NUH -> กด 'เสร็จสิ้น'\\n3. เภสัชกรเห็นสถานะ 'ชำระเงินแล้ว' -> พิมพ์ฉลากยา/จัดยา -> กด 'จ่ายยา' + เรียกคิว", criteria: "ตัด Stock ยาสำเร็จ ออกใบเสร็จเรียบร้อย และปิด Visit OPD สมบูรณ์" },
                { id: "SC-02 [B]", flow: "IPD", name: "NUH: แพทย์วินิจฉัยแล้วสั่ง Admit โดยไม่มี Order", desc: "แพทย์ NUH วินิจฉัยแล้วสั่ง Admit ผู้ป่วย OPD เข้า IPD ทันทีโดยไม่สั่ง Order", role: "แพทย์ OPD / พยาบาล (NUH)", critical: false, steps: "1. พยาบาลเรียกคิว -> แพทย์เปิด EMR เปลี่ยนสถานะ 'พร้อม' -> ลงวินิจฉัย OPD Note\\n2. แพทย์ประเมิน 'ต้อง Admit' -> กดปุ่ม 'สร้าง Admit Order' จาก NUH-EMR -> กรอกฟอร์ม -> Save", criteria: "สถานะผู้ป่วยเปลี่ยนเป็น 'รอ Admit' และคำขอส่งไปศูนย์จัดการเตียง NUH" },
                { id: "SC-05", flow: "IPD", name: "NUH: จองเตียง -> สร้าง AN (ต่อเนื่องจาก Scenario 2 [B])", desc: "จนท.เตียง NUH จองเตียงและสร้าง AN ให้ผู้ป่วย Admit", role: "จนท. ศูนย์จัดการเตียง (NUH)", critical: true, steps: "1. เข้าเมนู ศูนย์จัดการเตียง NUH -> tab 'คำขอ Admit' -> ค้นหาผู้ป่วย -> กด 'จองเตียง'\\n2. เลือกวอร์ด/ประเภทเตียง/เตียง จากผังเตียง -> กดบันทึก\\n3. กลับ tab 'คำขอ Admit' -> กดปุ่ม 'สร้าง AN'", criteria: "ระบบ Generate AN สำเร็จ ข้อมูลย้ายไปแสดงใน tab 'AN'" },
                { id: "SC-06", flow: "IPD", name: "NUH: ผู้ป่วยใน -> รายการเตียง หอผู้ป่วยใน", desc: "พยาบาล Ward NUH เปิดรายการเตียงหอผู้ป่วยในและบันทึกเวลาผู้ป่วยมาถึงวอร์ด", role: "พยาบาล Ward (NUH)", critical: false, steps: "1. เข้าเมนู ผู้ป่วยใน -> รายการเตียง -> เลือก Ward NUH -> กด ส่ง\\n2. ไปที่ tab 'เตียงทั้งหมด' -> เลือกผู้ป่วย -> กด 3 จุด -> เลือก 'บันทึกมาถึงวอร์ด' -> บันทึกเวลา", criteria: "บันทึกเวลาผู้ป่วยมาถึงวอร์ดสำเร็จ ผู้ป่วยแสดงสถานะพร้อมรับการดูแลบน Ward" },
                { id: "SC-07", flow: "IPD", name: "NUH: แพทย์ตรวจ + วินิจฉัย + สั่ง Order (Lab/X-ray/ยา)", desc: "แพทย์ Round ตรวจและสั่ง Order ยา/Lab/X-ray แบบ ONE DAY และ CONTINUE ให้ผู้ป่วย IPD NUH", role: "แพทย์ IPD (NUH)", critical: true, steps: "1. เปิด EMR IPD NUH (ค้นด้วย AN) -> เข้าเมนู 'IPD Summary' -> บันทึก Progress Note\\n2. เข้า tab 'Physician Order' -> สั่งออเดอร์ทั้ง 'One Day Order' และ 'Continue Order'\\n3. กด บันทึก -> กดปุ่ม 'Sign All'", criteria: "Order แสดงใน tab IPD Summary แยกกลุ่ม One Day / Continue ชัดเจน Status = 'รอรับ'" },
                { id: "SC-08", flow: "IPD", name: "NUH: พยาบาลตรวจสอบ Order ยา และ Confirm รายการยา", desc: "พยาบาลตรวจสอบและ Confirm รายการยาผู้ป่วย IPD แพทย์สั่ง Order ทั้งแบบ ONE DAY และ CONTINUE", role: "พยาบาล Ward (NUH)", critical: false, steps: "1. เข้าเมนู ผู้ป่วยใน -> รายการเตียง -> เลือก Ward -> เปิดหน้า 'Patient IPD Summary'\\n2. ตรวจสอบคอลัมน์ 'ORDER FOR ONE DAY' และ 'NEW ORDER FOR CONTINUE'\\n3. ตรวจสอบชื่อยา/ขนาด/วิธีใช้ -> กดปุ่ม 'รับออเดอร์' ทุกรายการ", criteria: "สถานะ Order เปลี่ยนเป็นรับออเดอร์แล้ว และรายการถูกส่งไปห้องยา IPD" },
                { id: "SC-09", flow: "IPD", name: "NUH: เภสัชกรรมจ่ายยา IPD [ONE DAY] (สร้างใบยา) -> ชำระเงิน -> เภสัชกรรม จ่ายยา -> พยาบาล Ward", desc: "เภสัชกรจ่ายยาผู้ป่วย IPD พร้อมกัน X ราย แยกตามประเภท Order ONE DAY และต้องชำระเงิน", role: "เภสัชกร IPD / การเงิน / พยาบาล Ward (NUH)", critical: false, steps: "1. เภสัชกรเข้า tab 'Order รอยืนยัน' -> ตรวจสอบยา One Day -> กด 'สร้างใบยา' (พิมพ์ฉลาก auto) -> ยืนยันใบยา\\n2. การเงินออกใบแจ้งหนี้ -> รับชำระเงิน\\n3. เภสัชกรเห็นสถานะ 'ชำระเงินแล้ว' -> จัดยา -> กด 'จ่ายยา'", criteria: "รายการยา One Day วิ่งไปแสดงบน e-MAR ของพยาบาล Ward พร้อมจ่ายยา" },
                { id: "SC-10", flow: "IPD", name: "NUH: เภสัชกรรมจ่ายยา IPD [CONTINUE] (สร้างใบยา) -> เภสัชกรรม จ่ายยา -> พยาบาล Ward", desc: "เภสัชกรจ่ายยาผู้ป่วย IPD พร้อมกัน X ราย แยกตามประเภท CONTINUE โดยไม่รอการชำระเงิน", role: "เภสัชกร IPD / พยาบาล Ward (NUH)", critical: false, steps: "1. เภสัชกรเข้าเมนู 'รับ Continue Order ประจำวัน' -> เลือก Ward -> กด ค้นหา\\n2. กดปุ่ม 'Generate ที่เลือก' -> ระบบสร้างใบยา Continue\\n3. พิมพ์ฉลากยา -> กด 'จ่ายยา' (ไม่ต้องรอชำระเงิน)", criteria: "รายการยา Continue ประจำวันถูก Generate และแสดงบน e-MAR ของ Ward ทันที" },
                { id: "SC-11", flow: "IPD", name: "NUH: จนท. Lab check-in + ลงผล + แพทย์อ่านผล", desc: "จนท. Lab ดำเนินการตรวจและบันทึกผลผู้ป่วย IPD ตามประเภท Order ONE DAY", role: "จนท. Lab / แพทย์ IPD (NUH)", critical: false, steps: "1. จนท. Lab เข้า รายการแล็บ -> tab 'รอเช็คอิน' -> กด เช็คอิน -> เลือกประเภทตัวอย่าง -> กด เก็บแล้ว (Container) -> กด รับแล้ว\\n2. ลงผล Lab -> บันทึกร่าง -> กด Final Report\\n3. แพทย์เปิด Patient Profile IPD -> เมนู Lab result เพื่อดูผล", criteria: "สถานะ Lab Task = 'เสร็จสิ้น' (Result completed) และแพทย์เห็นผลในระบบ" },
                { id: "SC-12", flow: "IPD", name: "NUH: จนท. Xray check-in + ลงผล + แพทย์อ่านผล", desc: "จนท. Xray ดำเนินการตรวจและบันทึกผลผู้ป่วย IPD พร้อมกัน X ราย แยกตามประเภท Order ONE DAY", role: "จนท. X-ray / พยาบาล / แพทย์อ่านผล (NUH)", critical: false, steps: "1. จนท. X-ray ไป tab 'รอ Check-in' -> เช็คอิน -> กด 'เริ่มถ่ายภาพ' -> กด 'ถ่ายภาพแล้ว' -> เลือกแพทย์อ่านผล\\n2. พยาบาลลงบันทึก Nurse Note / Imaging Nurse Note\\n3. แพทย์ลงรายงานผลตรวจรังสี -> กด บันทึก", criteria: "สถานะ Log = อ่านผล และรายงานผลรังสีแสดงใน EMR สมบูรณ์" },
                { id: "SC-13", flow: "IPD", name: "NUH: การเงินเรียกเก็บระหว่างพักรักษา (Interim Billing)", desc: "ญาติผู้ป่วยชำระค่ารักษาสะสมของผู้ป่วย IPD ทุก 3 วัน ตลอดช่วงพักรักษาในโรงพยาบาล NUH", role: "การเงิน (Cashier IPD NUH)", critical: false, steps: "1. เข้าเมนู Cashier ค้นหาผู้ป่วย IPD -> ดูรายการค่าใช้จ่ายสะสม (ยา/Lab/X-ray/ค่าห้อง)\\n2. ตรวจสอบสิทธิ -> เลือกรายการค่าใช้จ่าย -> กด 'สร้างใบแจ้งหนี้' (Interim Bill)\\n3. เลือกสิทธิ/วิธีชำระ -> กด จ่าย + ยืนยัน", criteria: "ระบบหักยอดชำระแล้วออกจากยอดค้างสะสม และตั้งรอบบันทึกใหม่สำหรับรอบถัดไป" },
                { id: "SC-14", flow: "IPD", name: "NUH: Discharge Process (ปิดยอดครั้งสุดท้าย)", desc: "แพทย์อนุมัติจำหน่ายผู้ป่วย IPD แล้วจนท.การเงินปิด Bill ยอดคงเหลือทั้งหมดและปลดเตียงคืนระบบ NUH", role: "แพทย์ IPD / การเงิน IPD (NUH)", critical: true, steps: "1. แพทย์บันทึก Discharge Summary + ลงวินิจฉัยสุดท้าย + สั่งยากลับบ้าน -> กด ยืนยัน Discharge\\n2. การเงินเปิดรายการ IPD รอปิด Bill -> ออกใบแจ้งหนี้ยอดสุดท้าย -> กด จ่าย + ยืนยัน -> ออกใบเสร็จ\\n3. การเงินกดปุ่ม 'ปิด Admission'", criteria: "รายชื่อผู้ป่วยย้ายไป tab 'ผู้ป่วยจำหน่าย' (Status = เสร็จสิ้น) และปลดเตียงคืนระบบสำเร็จ" },
                { id: "SC-15", flow: "OPD / IPD", name: "NUH: จนท. จากทุกแผนกเข้าสั่งพิมพ์ report จากเมนู รายงาน", desc: "เจ้าหน้าที่แต่ละแผนกละคน เข้ามาออกรายงานที่เมนูออกรายงาน NUH", role: "จนท. ทุกแผนก (NUH)", critical: false, steps: "1. เข้าเมนู รายงาน (Report) -> เลือกประเภทรายงานตามแผนก NUH\\n2. ทดสอบกด สั่งพิมพ์ (Print) สรุปยอด\\n3. ทดสอบกด ดาวน์โหลด (Download) สรุปยอด", criteria: "สั่งออกรายงานได้สำเร็จ ข้อมูลในไฟล์ PDF/Excel ถูกต้องครบถ้วน" },
                { id: "SC-16", flow: "OPD / IPD", name: "NUH: จนท. Coder เข้าเมนู เบิกจ่าย เพื่อลงรหัสโรค", desc: "เจ้าหน้าที่แผนก Coder เข้ามาลงรหัสโรคของผู้ป่วย NUH", role: "จนท. Coder (NUH)", critical: false, steps: "1. เข้าเมนู เบิกจ่าย -> OPD/IPD -> รายการรอรหัสโรค -> เลือกผู้ป่วยสถานะ 'รอลงรหัส'\\n2. ไปที่ Patient Profile -> เลือก Diagnosis + Procedure -> กด บันทึก\\n3. กดปุ่ม '>' เพื่อลงรหัสคนถัดไป", criteria: "สถานะผู้ป่วยเปลี่ยนเป็น 'ลงรหัสแล้ว' และย้ายไปแสดงใน tab ลงรหัสแล้ว" }
            ],
            SBH: [
                { id: "SC-01", flow: "OPD", name: "SBH: ลงทะเบียน คัดกรอง คิว OPD (รพ.สระบุรี)", desc: "ผู้ป่วย Walk-in ลงทะเบียนระบบ SBH-HIS แล้วส่งคัดกรอง และ เข้าคิว OPD สระบุรี", role: "เวชระเบียน / พยาบาลคัดกรอง (SBH)", critical: true, steps: "1. ค้นหา/สร้าง HN ระบบ SBH -> ลงทะเบียน Visit -> ออกใบนำทาง\\n2. พยาบาลคัดกรองตรวจ Vital Sign -> คัดกรองระดับความรุนแรง -> จัดคิวตรวจห้องตรวจสระบุรี\\n3. พยาบาลหน้าห้องตรวจ กดเรียกคิว -> กด 'พร้อมตรวจ'", criteria: "ผู้ป่วยขึ้นสถานะกำลังดำเนินการ และคิวแสดงหน้าห้องตรวจ SBH" },
                { id: "SC-02 [A]", flow: "OPD", name: "SBH: แพทย์ตรวจ OPD + สั่งออเดอร์ (Lab/X-ray/ยา)", desc: "แพทย์ห้องตรวจ OPD รพ.สระบุรี ตรวจผู้ป่วยและสั่งออเดอร์รักษาผ่าน SBH-EMR", role: "แพทย์ OPD (SBH)", critical: false, steps: "1. แพทย์เปิด SBH-EMR -> บันทึก Diagnosis (ICD-10)\\n2. สั่ง Lab/Xray/ยา เข้าตะกร้าออเดอร์ -> กดส่งคำสั่งตรวจรักษา", criteria: "บันทึกออเดอร์สำเร็จ สถานะเปลี่ยนเป็นพักการตรวจรอผล" },
                { id: "SC-03", flow: "OPD", name: "SBH: ส่งตรวจ Lab/X-ray -> ประมวลผล -> แพทย์สรุปตรวจเสร็จ", desc: "จนท. Lab/X-ray SBH รายงานผล และแพทย์อ่านผลสรุปสั่งยาจบ Visit OPD", role: "จนท. Lab/X-ray / แพทย์ OPD (SBH)", critical: false, steps: "1. ห้องแล็บสระบุรีเช็คอินสิ่งส่งตรวจ -> ลงผล Lab -> รายงานผล Final\\n2. แพทย์อ่านผลใน EMR -> สั่งยาเพิ่ม/สรุปผลการรักษา -> กดตรวจเสร็จ", criteria: "ผลตรวจเข้า EMR สมบูรณ์ และปิดตรวจ OPD เสียค่าใช้จ่าย" },
                { id: "SC-04", flow: "OPD", name: "SBH: ห้องยา OPD สร้างใบยา -> การเงินเก็บเงิน -> จ่ายยา", desc: "เภสัชกรรมและงานการเงิน SBH ตัดสต็อก ออกใบเสร็จ และจ่ายยาปิด Visit", role: "เภสัชกร / การเงิน (SBH)", critical: false, steps: "1. เภสัชกรยืนยันออเดอร์ยา -> การเงินเรียกเก็บและออกใบเสร็จ\\n2. เภสัชกรจัดยา -> ตรวจสอบการชำระเงิน -> จ่ายยาให้ผู้ป่วย", criteria: "ตัดสต็อกยา SBH เรียบร้อย ใบเสร็จออกสมบูรณ์" },
                { id: "SC-02 [B]", flow: "IPD", name: "SBH: แพทย์ประเมินสั่ง Admit เข้าวอร์ด IPD สระบุรี", desc: "แพทย์ OPD สระบุรี ประเมินอาการแล้วสร้างคำสั่ง Admit สั่งนอนโรงพยาบาล", role: "แพทย์ OPD (SBH)", critical: false, steps: "1. แพทย์เปิด EMR ประเมินเคสหนัก -> เลือกสร้างคำขอ Admit Order สระบุรี\\n2. บันทึกเหตุผลการนอน รพ. -> ยืนยันส่งคำขอไปศูนย์จองเตียง", criteria: "ผู้ป่วยเปลี่ยนสถานะเป็นรอ Admit สระบุรี" },
                { id: "SC-05", flow: "IPD", name: "SBH: ศูนย์เตียงสระบุรีจัดสรรเตียง + ออกเลข AN", desc: "เจ้าหน้าที่ศูนย์บริหารเตียง SBH จองเตียงตามวอร์ดและเปิด AN ผู้ป่วยใน", role: "ศูนย์จัดการเตียง (SBH)", critical: true, steps: "1. ค้นหาคำขอ Admit -> เลือกหอผู้ป่วยในสระบุรี -> เลือกเตียงว่าง\\n2. กดยืนยันจัดสรรเตียง -> กดเปิดสร้าง AN ผู้ป่วยใน SBH", criteria: "ได้เลข AN ผู้ป่วยใน SBH สำเร็จ เตียงถูกล็อกให้ผู้ป่วย" },
                { id: "SC-06", flow: "IPD", name: "SBH: พยาบาลวอร์ดรับผู้ป่วยเข้าเตียง (Arrival)", desc: "พยาบาลประจำวอร์ด SBH ลงรับตัวผู้ป่วยเข้าพักบนเตียงจริง", role: "พยาบาล Ward (SBH)", critical: false, steps: "1. เปิดตารางเตียงวอร์ด -> เลือกเคส -> บันทึกเวลาผู้ป่วยเดินทางมาถึงวอร์ด SBH", criteria: "ผู้ป่วยขึ้นสถานะเข้าพักบนวอร์ดเรียบร้อย" },
                { id: "SC-07", flow: "IPD", name: "SBH: แพทย์เจ้าของไข้ Round ตรวจ + สั่ง IPD Orders", desc: "แพทย์ IPD สระบุรี สั่งออเดอร์รักษา One Day และ Continue ประจำวัน", role: "แพทย์ IPD (SBH)", critical: true, steps: "1. เปิด EMR IPD SBH -> บันทึก Progress Note\\n2. สั่งยา/Lab/Xray แบบ One Day และ Continue -> กด Sign ยืนยัน", criteria: "ออเดอร์ย้ายไปหน้า IPD Summary สถานะรอพยาบาลรับคำสั่ง" },
                { id: "SC-08", flow: "IPD", name: "SBH: พยาบาล Ward ยืนยันรับออเดอร์ยาประจำวัน", desc: "พยาบาลวอร์ดตรวจสอบและกดยืนยันรับคำสั่งยาเพื่อส่งห้องยา IPD สระบุรี", role: "พยาบาล Ward (SBH)", critical: false, steps: "1. ตรวจสอบรายการยา One Day / Continue -> กดรับออเดอร์ยาส่งห้องยา", criteria: "ออเดอร์ส่งถึงระบบห้องยา IPD สระบุรี" },
                { id: "SC-09", flow: "IPD", name: "SBH: เภสัช IPD จัดยา One Day -> การเงินคิดเงิน -> จ่ายยา", desc: "กระบวนการจ่ายยา One Day ผู้ป่วยในสระบุรี พร้อมตัดสต็อก", role: "เภสัชกร IPD / การเงิน (SBH)", critical: false, steps: "1. เภสัชกรสร้างใบยา One Day -> การเงินคิดเงิน -> เภสัชกรจ่ายยาลง e-MAR", criteria: "รายการยาแสดงบน e-MAR ของพยาบาลวอร์ด SBH" },
                { id: "SC-10", flow: "IPD", name: "SBH: เภสัช IPD จ่ายยา Continue ประจำวันลง e-MAR", desc: "จัดและจ่ายยา Continue ประจำวันรอบเช้า/เย็น ให้ผู้ป่วยในสระบุรี", role: "เภสัชกร IPD (SBH)", critical: false, steps: "1. ดึงรายการยา Continue ประจำวัน -> พิมพ์ฉลากยา -> กดจ่ายยาลง e-MAR", criteria: "ยาประจำวันเข้า e-MAR พร้อมพยาบาลให้ยา" },
                { id: "SC-11", flow: "IPD", name: "SBH: รายงานผล Lab ผู้ป่วยใน รพ.สระบุรี", desc: "ห้องแล็บสระบุรีเก็บสิ่งส่งตรวจ รายงานผล Lab เคสผู้ป่วยใน", role: "จนท. Lab / แพทย์ IPD (SBH)", critical: false, steps: "1. เช็คอินสิ่งส่งตรวจ IPD -> ลงผลแล็บ -> กด Final Report สระบุรี", criteria: "ผลแล็บแสดงใน EMR IPD สระบุรี" },
                { id: "SC-12", flow: "IPD", name: "SBH: ถ่ายภาพและรายงานผล X-ray ผู้ป่วยใน", desc: "งานรังสีสระบุรี ถ่าย X-ray เตียง/ห้องรังสี และรายงานผลเอกซเรย์", role: "จนท. รังสี / แพทย์ (SBH)", critical: false, steps: "1. ถ่ายภาพรังสีผู้ป่วยใน -> แพทย์อ่านผลและบันทึกรายงานรังสี", criteria: "ผล X-ray พร้อมภาพถ่ายเข้าระบบ PACS/EMR SBH" },
                { id: "SC-13", flow: "IPD", name: "SBH: การเงินตั้งบิลเรียกเก็บเงินระหว่างกาล (Interim Bill)", desc: "สรุปและตั้งบิลเรียกเก็บค่ารักษาผู้ป่วยในทุก 3 วัน รพ.สระบุรี", role: "การเงิน IPD (SBH)", critical: false, steps: "1. สรุปค่าใช้จ่ายสะสม -> สร้างใบแจ้งหนี้ Interim Bill -> รับชำระเงิน", criteria: "ยอดค้างชำระหักออก และเริ่มนับรอบ 3 วันถัดไป" },
                { id: "SC-14", flow: "IPD", name: "SBH: แพทย์อนุมัติ Discharge + การเงินปิด Bill จำหน่าย", desc: "สรุป Discharge Summary ยาจำหน่ายบ้าน ปิดบิล และคืนเตียงสระบุรี", role: "แพทย์ IPD / การเงิน IPD (SBH)", critical: true, steps: "1. แพทย์บันทึก Discharge Summary + สั่งยากลับบ้าน\\n2. การเงินคิดเงินยอดสุดท้าย -> ปิดบิล AN -> ปลดเตียงคืนวอร์ด", criteria: "ผู้ป่วยเปลี่ยนสถานะเป็นจำหน่ายแล้ว เตียงสระบุรีว่างพร้อมรับเคสใหม่" },
                { id: "SC-15", flow: "OPD / IPD", name: "SBH: ออกรายงานสรุปประจำวันทุกแผนก (SBH Reports)", desc: "ทดสอบพิมพ์และดาวน์โหลดรายงานประจำวันของทุกแผนก รพ.สระบุรี", role: "จนท. ทุกแผนก (SBH)", critical: false, steps: "1. เลือกรายงานประจำวัน -> พิมพ์และดาวน์โหลดไฟล์ PDF/Excel สระบุรี", criteria: "รายงานออกถูกต้อง ตรงตามข้อมูลจริง" },
                { id: "SC-16", flow: "OPD / IPD", name: "SBH: Coder สรุปและลงรหัสโรค ICD-10 / ICD-9 สระบุรี", desc: "เจ้าหน้าที่เวชสถิติตรวจสอบเอกสารและลงรหัสโรคเพื่อเบิกจ่าย", role: "Coder / เวชสถิติ (SBH)", critical: false, steps: "1. เลือกผู้ป่วยรอลงรหัส -> บันทึก Diagnosis & Procedure Code -> บันทึกส่งเบิก", criteria: "สถานะเปลี่ยนเป็นลงรหัสแล้ว" }
            ],
            TMH: [
                { id: "SC-01", flow: "OPD", name: "TMH: คัดกรองและลงทะเบียนผู้ป่วย (เวชศาสตร์เขตร้อน)", desc: "กระบวนการรับผู้ป่วยคัดกรองลงทะเบียน โรงพยาบาลเวชศาสตร์เขตร้อน", role: "เวชระเบียน / พยาบาลคัดกรอง (TMH)", critical: true, steps: "1. สร้าง/ค้นหา HN TMH -> ออก Visit คลินิกเวชศาสตร์เขตร้อน -> พิมพ์ใบนำทาง\\n2. บันทึก Vital Sign คัดกรอง -> ส่งคิวเข้าห้องตรวจ TMH", criteria: "คิวขึ้นแสดงหน้าห้องตรวจ รพ.เวชศาสตร์เขตร้อน" },
                { id: "SC-02 [A]", flow: "OPD", name: "TMH: แพทย์ออกตรวจ ตรวจรักษา สั่ง Order เฉพาะทาง", desc: "แพทย์ตรวจและสั่งตรวจแล็บเฉพาะทาง/รังสี/ยา ใน TMH-EMR", role: "แพทย์ OPD (TMH)", critical: false, steps: "1. เรียกคิวตรวจ -> ลงผลวินิจฉัย OPD Note TMH\\n2. สั่ง Order แล็บเฉพาะทางเขตร้อน / X-ray / ยา -> ส่งออเดอร์", criteria: "ออเดอร์ส่งเข้าระบบห้องแล็บและห้องยา TMH สำเร็จ" },
                { id: "SC-03", flow: "OPD", name: "TMH: ตรวจแล็บเฉพาะทาง -> ออกผล -> แพทย์สรุปตรวจเสร็จ", desc: "กระบวนการตรวจแล็บเขตร้อนและแพทย์อ่านผลสรุปการรักษา OPD", role: "จนท. Lab / แพทย์ (TMH)", critical: false, steps: "1. ห้องแล็บ TMH ตรวจและอนุมัติผล Final Report\\n2. แพทย์อ่านผลใน EMR -> สั่งยา/นัดหมาย -> สรุปตรวจเสร็จ", criteria: "ผลแล็บเขตร้อนอนุมัติสมบูรณ์ แพทย์ปิดตรวจ OPD" },
                { id: "SC-04", flow: "OPD", name: "TMH: เภสัชสร้างใบยา -> การเงินเก็บเงิน -> จ่ายยาเขตร้อน", desc: "งานเภสัชกรรมและชำระเงิน OPD โรงพยาบาลเวชศาสตร์เขตร้อน", role: "เภสัชกร / การเงิน (TMH)", critical: false, steps: "1. เภสัชยืนยันรายการยา -> การเงินออกใบเสร็จรับเงิน\\n2. เภสัชกรจัดและจ่ายยาเฉพาะทาง -> ปิด Visit OPD TMH", criteria: "ตัดสต็อกยาสำเร็จ ออกใบเสร็จ TMH เรียบร้อย" },
                { id: "SC-02 [B]", flow: "IPD", name: "TMH: แพทย์สั่ง Admit ผู้ป่วยเข้าพักรักษาในโรงพยาบาล", desc: "แพทย์สั่งนอนโรงพยาบาลเวชศาสตร์เขตร้อนเพื่อสังเกตอาการและรักษา", role: "แพทย์ OPD (TMH)", critical: false, steps: "1. แพทย์สร้างคำสั่ง Admit Order ใน EMR TMH -> ระบุวอร์ดและเหตุผลการ Admit", criteria: "คำสั่ง Admit ส่งถึงศูนย์จัดการเตียง TMH" },
                { id: "SC-05", flow: "IPD", name: "TMH: จัดสรรเตียงผู้ป่วยใน + เปิดเลข AN TMH", desc: "เจ้าหน้าที่เตียงจัดเตียงวอร์ดเขตร้อนและออกเลข AN", role: "ศูนย์เตียง (TMH)", critical: true, steps: "1. เลือกหอผู้ป่วยใน TMH -> ล็อกเตียง -> กดปุ่มสร้างเลข AN ผู้ป่วยใน", criteria: "ได้เลข AN ผู้ป่วยใน รพ.เวชศาสตร์เขตร้อน" },
                { id: "SC-06", flow: "IPD", name: "TMH: พยาบาลวอร์ดรับตัวผู้ป่วยเข้าพักบนเตียง (Arrival)", desc: "พยาบาลประจำวอร์ดเวชศาสตร์เขตร้อน ลงบันทึกเวลาผู้ป่วยมาถึงเตียง", role: "พยาบาล Ward (TMH)", critical: false, steps: "1. เลือกเตียงผู้ป่วย -> บันทึกเวลาผู้ป่วยมาถึงวอร์ด TMH", criteria: "สถานะเตียงเปลี่ยนเป็นมีผู้ป่วยเข้าพัก" },
                { id: "SC-07", flow: "IPD", name: "TMH: แพทย์ Round ตรวจ + สั่ง Order IPD ประจำวัน", desc: "แพทย์ Round ตรวจอาการผู้ป่วยในและสั่ง Order ยา/Lab ใน TMH-EMR", role: "แพทย์ IPD (TMH)", critical: true, steps: "1. บันทึก Progress Note -> สั่ง Order One Day และ Continue ประจำวัน -> เซ็นอนุมัติ Sign All", criteria: "ออเดอร์แสดงบน IPD Summary รอพยาบาลยืนยัน" },
                { id: "SC-08", flow: "IPD", name: "TMH: พยาบาลวอร์ดตรวจสอบและยืนยันรับออเดอร์ยา", desc: "พยาบาลวอร์ด TMH ตรวจสอบวิธีใช้ยาและกดรับออเดอร์ส่งห้องยา", role: "พยาบาล Ward (TMH)", critical: false, steps: "1. ตรวจสอบชื่อยาและขนาด -> กดรับออเดอร์ยาส่งห้องยา IPD TMH", criteria: "ออเดอร์ส่งถึงห้องยา IPD เวชศาสตร์เขตร้อน" },
                { id: "SC-09", flow: "IPD", name: "TMH: ห้องยาจัดยา One Day -> คิดเงิน -> ส่งลง e-MAR", desc: "จัดและจ่ายยา One Day สำหรับผู้ป่วยใน รพ.เวชศาสตร์เขตร้อน", role: "เภสัชกร IPD / การเงิน (TMH)", critical: false, steps: "1. เภสัชกรพิมพ์ฉลากยา -> การเงินคิดเงิน -> จ่ายยาลง e-MAR วอร์ด", criteria: "ยาแสดงบน e-MAR พร้อมให้พยาบาลจ่ายยา" },
                { id: "SC-10", flow: "IPD", name: "TMH: ห้องยา Generate ยา Continue ประจำวันลง e-MAR", desc: "จัดจ่ายยา Continue ประจำวันสำหรับผู้ป่วยใน TMH", role: "เภสัชกร IPD (TMH)", critical: false, steps: "1. Generate ยา Continue ประจำวัน -> พิมพ์ฉลาก -> กดจ่ายยาลง e-MAR", criteria: "รายการยาประจำวันเข้า e-MAR สมบูรณ์" },
                { id: "SC-11", flow: "IPD", name: "TMH: ห้องแล็บตรวจและรายงานผล Lab ผู้ป่วยใน", desc: "งานห้องปฏิบัติการ TMH รายงานผลแล็บผู้ป่วยใน", role: "จนท. Lab / แพทย์ (TMH)", critical: false, steps: "1. เช็คอินสิ่งส่งตรวจ -> ลงผลแล็บเฉพาะทาง -> อนุมัติผล Final Report", criteria: "ผลแล็บแสดงใน EMR IPD TMH" },
                { id: "SC-12", flow: "IPD", name: "TMH: งานรังสีถ่ายภาพและรายงานผล X-ray ผู้ป่วยใน", desc: "ถ่าย X-ray และอ่านผลรายงานทางรังสี รพ.เวชศาสตร์เขตร้อน", role: "จนท. รังสี / แพทย์ (TMH)", critical: false, steps: "1. ถ่ายภาพรังสี -> แพทย์อ่านผลและบันทึกรายงานผลเอกซเรย์", criteria: "ผลรังสีเข้า EMR TMH เรียบร้อย" },
                { id: "SC-13", flow: "IPD", name: "TMH: การเงินออกบิลเรียกเก็บเงินระหว่างกาล (Interim Bill)", desc: "สรุปยอดและออกบิลชำระเงินสะสมผู้ป่วยในทุก 3 วัน TMH", role: "การเงิน IPD (TMH)", critical: false, steps: "1. ตรวจสอบค่าใช้จ่ายสะสม -> สร้าง Interim Bill -> รับชำระเงิน", criteria: "ยอดค้างชำระตัดหักสมบูรณ์" },
                { id: "SC-14", flow: "IPD", name: "TMH: แพทย์อนุมัติ Discharge + การเงินปิด Bill จำหน่าย", desc: "สรุป Discharge Summary สั่งยากลับบ้าน ปิดบิล และคืนเตียง TMH", role: "แพทย์ IPD / การเงิน (TMH)", critical: true, steps: "1. บันทึก Discharge Summary -> สั่งยากลับบ้าน\\n2. การเงินปิดบิลยอดสุดท้าย -> ออกใบเสร็จ -> ปลดเตียงคืนวอร์ด TMH", criteria: "ผู้ป่วยย้ายไปสถานะจำหน่าย เตียง TMH ว่างพร้อมรับเคสใหม่" },
                { id: "SC-15", flow: "OPD / IPD", name: "TMH: ออกรายงานสรุปประจำวันทุกแผนก (TMH Reports)", desc: "ทดสอบพิมพ์และดาวน์โหลดรายงานประจำวันของ รพ.เวชศาสตร์เขตร้อน", role: "จนท. ทุกแผนก (TMH)", critical: false, steps: "1. เลือกและดาวน์โหลดไฟล์รายงาน PDF/Excel ประจำวัน TMH", criteria: "ไฟล์รายงานออกสมบูรณ์ถูกต้อง" },
                { id: "SC-16", flow: "OPD / IPD", name: "TMH: Coder สรุปและลงรหัสโรค ICD-10 / ICD-9 TMH", desc: "เจ้าหน้าที่เวชสถิติลงรหัสโรคเพื่อการส่งเบิก e-Claim รพ.เวชศาสตร์เขตร้อน", role: "Coder / เวชสถิติ (TMH)", critical: false, steps: "1. ตรวจสอบเอกสารผู้ป่วย -> บันทึก Diagnosis & Procedure Code TMH", criteria: "สถานะเปลี่ยนเป็นลงรหัสแล้ว" }
            ],
            Siriraj: [
                { id: "SC-01", flow: "OPD", name: "Siriraj: ลงทะเบียน คัดกรอง คิว OPD (รพ.ศิริราช)", desc: "ผู้ป่วย Walk-in ลงทะเบียนระบบ Si-HIS แล้วส่งคัดกรอง และ เข้าคิว OPD ศิริราช", role: "เวชระเบียน / พยาบาลคัดกรอง (Siriraj)", critical: true, steps: "1. ค้นหา/สร้าง HN ศิริราช -> ลงทะเบียน Visit -> ออกใบนำทาง\\n2. พยาบาลคัดกรองตรวจ Vital Sign -> ส่งคิวห้องตรวจศิริราช\\n3. พยาบาลกดเรียกคิว -> กด 'พร้อมตรวจ'", criteria: "คิวแสดงหน้าห้องตรวจ รพ.ศิริราช" },
                { id: "SC-02 [A]", flow: "OPD", name: "Siriraj: แพทย์ตรวจ OPD + สั่งออเดอร์ (Lab/X-ray/ยา)", desc: "แพทย์ห้องตรวจ OPD รพ.ศิริราช ตรวจผู้ป่วยและสั่งออเดอร์รักษาผ่าน Si-EMR", role: "แพทย์ OPD (Siriraj)", critical: false, steps: "1. เปิด Si-EMR -> ลงวินิจฉัย ICD-10 -> สั่งออเดอร์ Lab/X-ray/ยา -> กดส่งคำสั่ง", criteria: "ออเดอร์เข้าระบบ รพ.ศิริราช สำเร็จ" },
                { id: "SC-03", flow: "OPD", name: "Siriraj: ส่งตรวจ Lab/X-ray -> ประมวลผล -> แพทย์สรุปตรวจเสร็จ", desc: "จนท. Lab/X-ray ศิริราช รายงานผล และแพทย์อ่านผลสรุปสั่งยาจบ Visit OPD", role: "จนท. Lab/X-ray / แพทย์ (Siriraj)", critical: false, steps: "1. ห้องแล็บศิริราชลงผลแล็บ Final -> แพทย์อ่านผลใน EMR -> สั่งยาปิด Visit", criteria: "ผลตรวจเข้า EMR สมบูรณ์ แพทย์ปิดตรวจ OPD" },
                { id: "SC-04", flow: "OPD", name: "Siriraj: ห้องยา OPD สร้างใบยา -> การเงินเก็บเงิน -> จ่ายยา", desc: "เภสัชกรรมและงานการเงิน ศิริราช ตัดสต็อก ออกใบเสร็จ และจ่ายยาปิด Visit", role: "เภสัชกร / การเงิน (Siriraj)", critical: false, steps: "1. เภสัชยืนยันออเดอร์ยา -> การเงินคิดเงินออกใบเสร็จ -> เภสัชกรจ่ายยา", criteria: "ตัดสต็อกยาเรียบร้อย ออกใบเสร็จศิริราชสำเร็จ" },
                { id: "SC-02 [B]", flow: "IPD", name: "Siriraj: แพทย์ประเมินสั่ง Admit เข้าวอร์ด IPD ศิริราช", desc: "แพทย์ OPD ศิริราช ประเมินอาการแล้วสร้างคำสั่ง Admit สั่งนอนโรงพยาบาล", role: "แพทย์ OPD (Siriraj)", critical: false, steps: "1. เปิด EMR สร้างคำขอ Admit Order ศิริราช -> ยืนยันส่งศูนย์เตียง", criteria: "ผู้ป่วยเปลี่ยนสถานะเป็นรอ Admit ศิริราช" },
                { id: "SC-05", flow: "IPD", name: "Siriraj: ศูนย์เตียงศิริราชจัดสรรเตียง + ออกเลข AN", desc: "เจ้าหน้าที่ศูนย์บริหารเตียง ศิริราช จองเตียงตามวอร์ดและเปิด AN ผู้ป่วยใน", role: "ศูนย์จัดการเตียง (Siriraj)", critical: true, steps: "1. เลือกหอผู้ป่วยในศิริราช -> เลือกเตียง -> สร้างเลข AN ผู้ป่วยใน", criteria: "ได้เลข AN ผู้ป่วยใน ศิริราช สำเร็จ" },
                { id: "SC-06", flow: "IPD", name: "Siriraj: พยาบาลวอร์ดรับผู้ป่วยเข้าเตียง (Arrival)", desc: "พยาบาลประจำวอร์ด ศิริราช ลงรับตัวผู้ป่วยเข้าพักบนเตียงจริง", role: "พยาบาล Ward (Siriraj)", critical: false, steps: "1. บันทึกเวลาผู้ป่วยเดินทางมาถึงวอร์ด ศิริราช", criteria: "ผู้ป่วยเข้าพักบนวอร์ดเรียบร้อย" },
                { id: "SC-07", flow: "IPD", name: "Siriraj: แพทย์ Round ตรวจ + สั่ง IPD Orders", desc: "แพทย์ IPD ศิริราช สั่งออเดอร์รักษา One Day และ Continue ประจำวัน", role: "แพทย์ IPD (Siriraj)", critical: true, steps: "1. เปิด Si-EMR IPD -> บันทึก Progress Note -> สั่งยา/Lab/Xray -> กด Sign All", criteria: "ออเดอร์แสดงบน IPD Summary รอพยาบาลรับคำสั่ง" },
                { id: "SC-08", flow: "IPD", name: "Siriraj: พยาบาล Ward ยืนยันรับออเดอร์ยาประจำวัน", desc: "พยาบาลวอร์ดตรวจสอบและกดยืนยันรับคำสั่งยาเพื่อส่งห้องยา IPD ศิริราช", role: "พยาบาล Ward (Siriraj)", critical: false, steps: "1. ตรวจสอบรายการยา -> กดรับออเดอร์ยาส่งห้องยา IPD ศิริราช", criteria: "ออเดอร์ส่งถึงห้องยา IPD ศิริราช" },
                { id: "SC-09", flow: "IPD", name: "Siriraj: เภสัช IPD จัดยา One Day -> การเงินคิดเงิน -> จ่ายยา", desc: "กระบวนการจ่ายยา One Day ผู้ป่วยในศิริราช พร้อมตัดสต็อก", role: "เภสัชกร IPD / การเงิน (Siriraj)", critical: false, steps: "1. เภสัชสร้างใบยา One Day -> การเงินคิดเงิน -> จ่ายยาลง e-MAR", criteria: "รายการยาแสดงบน e-MAR วอร์ด ศิริราช" },
                { id: "SC-10", flow: "IPD", name: "Siriraj: เภสัช IPD จ่ายยา Continue ประจำวันลง e-MAR", desc: "จัดและจ่ายยา Continue ประจำวันให้ผู้ป่วยในศิริราช", role: "เภสัชกร IPD (Siriraj)", critical: false, steps: "1. Generate ยา Continue ประจำวัน -> พิมพ์ฉลาก -> กดจ่ายยาลง e-MAR", criteria: "ยาประจำวันเข้า e-MAR พร้อมให้ยา" },
                { id: "SC-11", flow: "IPD", name: "Siriraj: รายงานผล Lab ผู้ป่วยใน รพ.ศิริราช", desc: "ห้องแล็บศิริราชเก็บสิ่งส่งตรวจ รายงานผล Lab เคสผู้ป่วยใน", role: "จนท. Lab / แพทย์ (Siriraj)", critical: false, steps: "1. เช็คอินสิ่งส่งตรวจ -> ลงผลแล็บ -> กด Final Report ศิริราช", criteria: "ผลแล็บแสดงใน EMR IPD ศิริราช" },
                { id: "SC-12", flow: "IPD", name: "Siriraj: ถ่ายภาพและรายงานผล X-ray ผู้ป่วยใน", desc: "งานรังสีศิริราช ถ่าย X-ray และรายงานผลเอกซเรย์", role: "จนท. รังสี / แพทย์ (Siriraj)", critical: false, steps: "1. ถ่ายภาพรังสี -> แพทย์อ่านผลและบันทึกรายงานรังสี", criteria: "ผล X-ray เข้า EMR ศิริราช สมบูรณ์" },
                { id: "SC-13", flow: "IPD", name: "Siriraj: การเงินตั้งบิลเรียกเก็บเงินระหว่างกาล (Interim Bill)", desc: "สรุปและตั้งบิลเรียกเก็บค่ารักษาผู้ป่วยในทุก 3 วัน รพ.ศิริราช", role: "การเงิน IPD (Siriraj)", critical: false, steps: "1. สรุปค่าใช้จ่ายสะสม -> สร้าง Interim Bill -> รับชำระเงิน", criteria: "ยอดค้างชำระหักออกเรียบร้อย" },
                { id: "SC-14", flow: "IPD", name: "Siriraj: แพทย์อนุมัติ Discharge + การเงินปิด Bill จำหน่าย", desc: "สรุป Discharge Summary ยาจำหน่ายบ้าน ปิดบิล และคืนเตียงศิริราช", role: "แพทย์ IPD / การเงิน (Siriraj)", critical: true, steps: "1. แพทย์บันทึก Discharge Summary + สั่งยากลับบ้าน\\n2. การเงินปิดบิลยอดสุดท้าย -> ออกใบเสร็จ -> ปลดเตียงคืนวอร์ด ศิริราช", criteria: "ผู้ป่วยจำหน่ายสมบูรณ์ เตียงศิริราชว่างพร้อมรับเคสใหม่" },
                { id: "SC-15", flow: "OPD / IPD", name: "Siriraj: ออกรายงานสรุปประจำวันทุกแผนก (Siriraj Reports)", desc: "ทดสอบพิมพ์และดาวน์โหลดรายงานประจำวันของทุกแผนก รพ.ศิริราช", role: "จนท. ทุกแผนก (Siriraj)", critical: false, steps: "1. เลือกและดาวน์โหลดไฟล์รายงาน PDF/Excel ประจำวัน ศิริราช", criteria: "รายงานออกถูกต้อง ตรงตามข้อมูลจริง" },
                { id: "SC-16", flow: "OPD / IPD", name: "Siriraj: Coder สรุปและลงรหัสโรค ICD-10 / ICD-9 ศิริราช", desc: "เจ้าหน้าที่เวชสถิติตรวจสอบเอกสารและลงรหัสโรคเพื่อเบิกจ่าย", role: "Coder / เวชสถิติ (Siriraj)", critical: false, steps: "1. เลือกผู้ป่วยรอลงรหัส -> บันทึก Diagnosis & Procedure Code ศิริราช", criteria: "สถานะเปลี่ยนเป็นลงรหัสแล้ว" }
            ],
            Standard: [
                { id: "SC-01", flow: "OPD", name: "Standard: ลงทะเบียน คัดกรอง ก่อนเข้าตรวจ OPD", desc: "ผู้ป่วย Walk-in ลงทะเบียนแล้วถูกส่งต่อไปแผนกคัดกรอง และ เข้าคิว OPD", role: "เวชระเบียน / พยาบาลคัดกรอง / พยาบาล OPD", critical: true, steps: "1. ค้นหา/สร้าง HN -> ลงทะเบียน Visit -> พิมพ์ใบนำทาง\\n2. พยาบาลคัดกรองดู tab 'คำขอ Walk-in' -> บันทึก Vital Sign -> เลือกแพทย์/นัด -> พิมพ์บัตรคิว\\n3. คิวขึ้น tab 'รอเช็คอิน' -> กด Check-in -> กดเรียกคิว -> กด 'พร้อมตรวจ'", criteria: "สถานะผู้ป่วยเปลี่ยนเป็น 'กำลังดำเนินการ' และคิวแสดงหน้าห้องตรวจ" },
                { id: "SC-02 [A]", flow: "OPD", name: "Standard: แพทย์ตรวจ + วินิจฉัย + สั่ง Order (Lab/X-ray/ยา)", desc: "พยาบาลหน้าห้องตรวจกดเรียกคิว ตรวจผู้ป่วย OPD พร้อมกัน เพื่อเข้าห้องตรวจ แล้วสั่ง Order", role: "แพทย์ OPD / พยาบาลหน้าห้องตรวจ", critical: false, steps: "1. พยาบาลกดเรียกคิวเข้าห้องตรวจ\\n2. แพทย์เปิด EMR เปลี่ยนสถานะ 'พร้อม' -> บันทึก Diagnosis (ICD-10)\\n3. สั่ง Order ครบ 3 ชนิด (Lab + X-ray + ยา) ลงตะกร้า -> กด 'ส่งคำสั่ง' (Submit Order)", criteria: "ส่ง Order ทั้งหมดสำเร็จในครั้งเดียว และสถานะผู้ป่วยเปลี่ยนเป็น 'พักการตรวจ'" },
                { id: "SC-03", flow: "OPD", name: "Standard: ส่ง Lab/X-ray -> รับผล -> แพทย์อ่านผลต่อ", desc: "ระบบส่ง Order ไปห้อง Lab/X-ray และประมวลผล Lab/X-ray พร้อมแพทย์อ่านผลกลับเข้าตรวจต่อ", role: "จนท. Lab / แพทย์ OPD", critical: false, steps: "1. จนท. Lab เช็คอินรายการ -> เก็บตัวอย่าง (Container) -> ยืนยัน -> ลงผล Lab -> กด Final Report\\n2. แพทย์เปิด EMR ดูผล -> เปลี่ยนสถานะ 'พร้อม' -> สั่งยาเพิ่ม/นัดหมาย/ออกใบรับรองแพทย์ -> กด 'ตรวจเสร็จ'", criteria: "ผล Lab ออกสมบูรณ์ และแพทย์เปลี่ยนสถานะผู้ป่วยเป็น 'ตรวจเสร็จ'" },
                { id: "SC-04", flow: "OPD", name: "Standard: เภสัชกรรม (สร้างใบยา) -> ชำระเงิน -> เภสัชกรรม จ่ายยา -> การเงินปิด Visit", desc: "เภสัชกรสร้างใบยาส่งต่อการเงินชำระเงินแล้วเภสัชกรจ่ายยาปิด Visit ให้ผู้ป่วย OPD", role: "เภสัชกร OPD / การเงิน", critical: false, steps: "1. เภสัชกรตรวจใบสั่งยา -> กด 'สร้างใบยา' -> กด 'ยืนยันใบยา' (ตัด Stock ยา)\\n2. การเงินออกใบแจ้งหนี้ -> รับชำระเงิน -> พิมพ์ใบเสร็จ -> กด 'เสร็จสิ้น'\\n3. เภสัชกรเห็นสถานะ 'ชำระเงินแล้ว' -> พิมพ์ฉลากยา/จัดยา -> กด 'จ่ายยา' + เรียกคิว", criteria: "ตัด Stock ยาสำเร็จ ออกใบเสร็จเรียบร้อย และปิด Visit OPD สมบูรณ์" },
                { id: "SC-02 [B]", flow: "IPD", name: "Standard: แพทย์วินิจฉัยแล้วสั่ง Admit โดยไม่มี Order", desc: "แพทย์วินิจฉัยแล้วสั่ง Admit ผู้ป่วย OPD เข้า IPD ทันทีโดยไม่สั่ง Order", role: "แพทย์ OPD / พยาบาล", critical: false, steps: "1. พยาบาลเรียกคิว -> แพทย์เปิด EMR เปลี่ยนสถานะ 'พร้อม' -> ลงวินิจฉัย OPD Note\\n2. แพทย์ประเมิน 'ต้อง Admit' -> กดปุ่ม 'สร้าง Admit Order' จาก EMR -> กรอกฟอร์ม -> Save", criteria: "สถานะผู้ป่วยเปลี่ยนเป็น 'รอ Admit' และคำขอส่งไปศูนย์จัดการเตียง" },
                { id: "SC-05", flow: "IPD", name: "Standard: จองเตียง -> สร้าง AN (ต่อเนื่องจาก Scenario 2 [B])", desc: "จนท.เตียงจองเตียงและสร้าง AN ให้ผู้ป่วย Admit", role: "จนท. ศูนย์จัดการเตียง", critical: true, steps: "1. เข้าเมนู ศูนย์จัดการเตียง -> tab 'คำขอ Admit' -> ค้นหาผู้ป่วย -> กด 'จองเตียง'\\n2. เลือกวอร์ด/ประเภทเตียง/เตียง จากผังเตียง -> กดบันทึก\\n3. กลับ tab 'คำขอ Admit' -> กดปุ่ม 'สร้าง AN'", criteria: "ระบบ Generate AN สำเร็จ ข้อมูลย้ายไปแสดงใน tab 'AN'" },
                { id: "SC-06", flow: "IPD", name: "Standard: ผู้ป่วยใน -> รายการเตียง หอผู้ป่วยใน", desc: "พยาบาล Ward เปิดรายการเตียงหอผู้ป่วยในและบันทึกเวลาผู้ป่วยมาถึงวอร์ด", role: "พยาบาล Ward", critical: false, steps: "1. เข้าเมนู ผู้ป่วยใน -> รายการเตียง -> เลือก Ward -> กด ส่ง\\n2. ไปที่ tab 'เตียงทั้งหมด' -> เลือกผู้ป่วย -> กด 3 จุด -> เลือก 'บันทึกมาถึงวอร์ด' -> บันทึกเวลา", criteria: "บันทึกเวลาผู้ป่วยมาถึงวอร์ดสำเร็จ ผู้ป่วยแสดงสถานะพร้อมรับการดูแลบน Ward" },
                { id: "SC-07", flow: "IPD", name: "Standard: แพทย์ตรวจ + วินิจฉัย + สั่ง Order (Lab/X-ray/ยา)", desc: "แพทย์ Round ตรวจและสั่ง Order ยา/Lab/X-ray แบบ ONE DAY และ CONTINUE ให้ผู้ป่วย IPD", role: "แพทย์ IPD", critical: true, steps: "1. เปิด EMR IPD (ค้นด้วย AN) -> เข้าเมนู 'IPD Summary' -> บันทึก Progress Note\\n2. เข้า tab 'Physician Order' -> สั่งออเดอร์ทั้ง 'One Day Order' และ 'Continue Order'\\n3. กด บันทึก -> กดปุ่ม 'Sign All'", criteria: "Order แสดงใน tab IPD Summary แยกกลุ่ม One Day / Continue ชัดเจน Status = 'รอรับ'" },
                { id: "SC-08", flow: "IPD", name: "Standard: พยาบาลตรวจสอบ Order ยา และ Confirm รายการยา", desc: "พยาบาลตรวจสอบและ Confirm รายการยาผู้ป่วย IPD แพทย์สั่ง Order ทั้งแบบ ONE DAY และ CONTINUE", role: "พยาบาล Ward", critical: false, steps: "1. เข้าเมนู ผู้ป่วยใน -> รายการเตียง -> เลือก Ward -> เปิดหน้า 'Patient IPD Summary'\\n2. ตรวจสอบคอลัมน์ 'ORDER FOR ONE DAY' และ 'NEW ORDER FOR CONTINUE'\\n3. ตรวจสอบชื่อยา/ขนาด/วิธีใช้ -> กดปุ่ม 'รับออเดอร์' ทุกรายการ", criteria: "สถานะ Order เปลี่ยนเป็นรับออเดอร์แล้ว และรายการถูกส่งไปห้องยา IPD" },
                { id: "SC-09", flow: "IPD", name: "Standard: เภสัชกรรมจ่ายยา IPD [ONE DAY] (สร้างใบยา) -> ชำระเงิน -> เภสัชกรรม จ่ายยา -> พยาบาล Ward", desc: "เภสัชกรจ่ายยาผู้ป่วย IPD พร้อมกัน X ราย แยกตามประเภท Order ONE DAY และต้องชำระเงิน", role: "เภสัชกร IPD / การเงิน / พยาบาล Ward", critical: false, steps: "1. เภสัชกรเข้า tab 'Order รอยืนยัน' -> ตรวจสอบยา One Day -> กด 'สร้างใบยา' (พิมพ์ฉลาก auto) -> ยืนยันใบยา\\n2. การเงินออกใบแจ้งหนี้ -> รับชำระเงิน\\n3. เภสัชกรเห็นสถานะ 'ชำระเงินแล้ว' -> จัดยา -> กด 'จ่ายยา'", criteria: "รายการยา One Day วิ่งไปแสดงบน e-MAR ของพยาบาล Ward พร้อมจ่ายยา" },
                { id: "SC-10", flow: "IPD", name: "Standard: เภสัชกรรมจ่ายยา IPD [CONTINUE] (สร้างใบยา) -> เภสัชกรรม จ่ายยา -> พยาบาล Ward", desc: "เภสัชกรจ่ายยาผู้ป่วย IPD พร้อมกัน X ราย แยกตามประเภท CONTINUE โดยไม่รอการชำระเงิน", role: "เภสัชกร IPD / พยาบาล Ward", critical: false, steps: "1. เภสัชกรเข้าเมนู 'รับ Continue Order ประจำวัน' -> เลือก Ward -> กด ค้นหา\\n2. กดปุ่ม 'Generate ที่เลือก' -> ระบบสร้างใบยา Continue\\n3. พิมพ์ฉลากยา -> กด 'จ่ายยา' (ไม่ต้องรอชำระเงิน)", criteria: "รายการยา Continue ประจำวันถูก Generate และแสดงบน e-MAR ของ Ward ทันที" },
                { id: "SC-11", flow: "IPD", name: "Standard: จนท. Lab check-in + ลงผล + แพทย์อ่านผล", desc: "จนท. Lab ดำเนินการตรวจและบันทึกผลผู้ป่วย IPD ตามประเภท Order ONE DAY", role: "จนท. Lab / แพทย์ IPD", critical: false, steps: "1. จนท. Lab เข้า รายการแล็บ -> tab 'รอเช็คอิน' -> กด เช็คอิน -> เลือกประเภทตัวอย่าง -> กด เก็บแล้ว (Container) -> กด รับแล้ว\\n2. ลงผล Lab -> บันทึกร่าง -> กด Final Report\\n3. แพทย์เปิด Patient Profile IPD -> เมนู Lab result เพื่อดูผล", criteria: "สถานะ Lab Task = 'เสร็จสิ้น' (Result completed) และแพทย์เห็นผลในระบบ" },
                { id: "SC-12", flow: "IPD", name: "Standard: จนท. Xray check-in + ลงผล + แพทย์อ่านผล", desc: "จนท. Xray ดำเนินการตรวจและบันทึกผลผู้ป่วย IPD พร้อมกัน X ราย แยกตามประเภท Order ONE DAY", role: "จนท. X-ray / พยาบาล / แพทย์อ่านผล", critical: false, steps: "1. จนท. X-ray ไป tab 'รอ Check-in' -> เช็คอิน -> กด 'เริ่มถ่ายภาพ' -> กด 'ถ่ายภาพแล้ว' -> เลือกแพทย์อ่านผล\\n2. พยาบาลลงบันทึก Nurse Note / Imaging Nurse Note\\n3. แพทย์ลงรายงานผลตรวจรังสี -> กด บันทึก", criteria: "สถานะ Log = อ่านผล และรายงานผลรังสีแสดงใน EMR สมบูรณ์" },
                { id: "SC-13", flow: "IPD", name: "Standard: การเงินเรียกเก็บระหว่างพักรักษา (Interim Billing)", desc: "ญาติผู้ป่วยชำระค่ารักษาสะสมของผู้ป่วย IPD ทุก 3 วัน ตลอดช่วงพักรักษาในโรงพยาบาล", role: "การเงิน (Cashier IPD)", critical: false, steps: "1. เข้าเมนู Cashier ค้นหาผู้ป่วย IPD -> ดูรายการค่าใช้จ่ายสะสม (ยา/Lab/X-ray/ค่าห้อง)\\n2. ตรวจสอบสิทธิ -> เลือกรายการค่าใช้จ่าย -> กด 'สร้างใบแจ้งหนี้' (Interim Bill)\\n3. เลือกสิทธิ/วิธีชำระ -> กด จ่าย + ยืนยัน", criteria: "ระบบหักยอดชำระแล้วออกจากยอดค้างสะสม และตั้งรอบบันทึกใหม่สำหรับรอบถัดไป" },
                { id: "SC-14", flow: "IPD", name: "Standard: Discharge Process (ปิดยอดครั้งสุดท้าย)", desc: "แพทย์อนุมัติจำหน่ายผู้ป่วย IPD แล้วจนท.การเงินปิด Bill ยอดคงเหลือทั้งหมดและปลดเตียงคืนระบบ", role: "แพทย์ IPD / การเงิน IPD", critical: true, steps: "1. แพทย์บันทึก Discharge Summary + ลงวินิจฉัยสุดท้าย + สั่งยากลับบ้าน -> กด ยืนยัน Discharge\\n2. การเงินเปิดรายการ IPD รอปิด Bill -> ออกใบแจ้งหนี้ยอดสุดท้าย -> กด จ่าย + ยืนยัน -> ออกใบเสร็จ\\n3. การเงินกดปุ่ม 'ปิด Admission'", criteria: "รายชื่อผู้ป่วยย้ายไป tab 'ผู้ป่วยจำหน่าย' (Status = เสร็จสิ้น) และปลดเตียงคืนระบบสำเร็จ" },
                { id: "SC-15", flow: "OPD / IPD", name: "Standard: จนท. จากทุกแผนกเข้าสั่งพิมพ์ report จากเมนู รายงาน", desc: "เจ้าหน้าที่แต่ละแผนกละคน เข้ามาออกรายงานที่เมนูออกรายงาน", role: "จนท. ทุกแผนก", critical: false, steps: "1. เข้าเมนู รายงาน (Report) -> เลือกประเภทรายงานตามแผนก\\n2. ทดสอบกด สั่งพิมพ์ (Print) สรุปยอด\\n3. ทดสอบกด ดาวน์โหลด (Download) สรุปยอด", criteria: "สั่งออกรายงานได้สำเร็จ ข้อมูลในไฟล์ PDF/Excel ถูกต้องครบถ้วน" },
                { id: "SC-16", flow: "OPD / IPD", name: "Standard: จนท. Coder เข้าเมนู เบิกจ่าย เพื่อลงรหัสโรค", desc: "เจ้าหน้าที่แผนก Coder เข้ามาลงรหัสโรคของผู้ป่วย", role: "จนท. Coder", critical: false, steps: "1. เข้าเมนู เบิกจ่าย -> OPD/IPD -> รายการรอรหัสโรค -> เลือกผู้ป่วยสถานะ 'รอลงรหัส'\\n2. ไปที่ Patient Profile -> เลือก Diagnosis + Procedure -> กด บันทึก\\n3. กดปุ่ม '>' เพื่อลงรหัสคนถัดไป", criteria: "สถานะผู้ป่วยเปลี่ยนเป็น 'ลงรหัสแล้ว' และย้ายไปแสดงใน tab ลงรหัสแล้ว" }
            ]
        };
"""

new_on_site_change = """
        function onSiteSelectChange() {
            let sel = document.getElementById('meta-site-select').value;
            let customGrp = document.getElementById('custom-site-group');
            let inputSite = document.getElementById('meta-site');

            if (sel === 'NUH') {
                customGrp.style.display = 'none';
                inputSite.value = 'NUH (โรงพยาบาลมหาวิทยาลัยนเรศวร)';
                activeScenarios = siteScenarioFlows.NUH;
            } else if (sel === 'SBH') {
                customGrp.style.display = 'none';
                inputSite.value = 'SBH (โรงพยาบาลสระบุรี)';
                activeScenarios = siteScenarioFlows.SBH;
            } else if (sel === 'TMH') {
                customGrp.style.display = 'none';
                inputSite.value = 'TMH (โรงพยาบาลเวชศาสตร์เขตร้อน)';
                activeScenarios = siteScenarioFlows.TMH;
            } else if (sel === 'Siriraj') {
                customGrp.style.display = 'none';
                inputSite.value = 'Siriraj Hospital (รพ.ศิริราช)';
                activeScenarios = siteScenarioFlows.Siriraj;
            } else if (sel === 'Standard') {
                customGrp.style.display = 'none';
                inputSite.value = 'Standard E2E Flow';
                activeScenarios = siteScenarioFlows.Standard;
            } else {
                customGrp.style.display = 'flex';
                activeScenarios = siteScenarioFlows.Standard;
            }
            
            saveMetadata();
            renderScenarios();
            updateMetrics();
        }
"""

# Replace siteScenarioFlows in HTML
html = re.sub(r'// Dedicated Scenario Suites per Hospital Site\n        const siteScenarioFlows = \{.*?\n        \};\n', site_scenarios_js + '\n', html, flags=re.DOTALL)
html = re.sub(r'function onSiteSelectChange\(\) \{.*?\n        \}', new_on_site_change, html, flags=re.DOTALL)

with open(html_path, 'w', encoding='utf-8') as f:
    f.write(html)

print('Successfully created dedicated scenario suites for all hospitals!')
